### ISSUE TITLE
Update version to [12.0.4] for [seafile] for ￥10

### ISSUE THREAD

**Issue by qiuf12** [Websoft9/docker-library#1034]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [ ] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs seafile_g5gp3
```
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Booting runit daemon...
*** Runit started as PID 20
*** Running /scripts/enterpoint.sh...
2024-12-09 08:33:01 Waiting Nginx 
2024-12-09 08:33:01 Nginx ready 
2024-12-09 08:33:02 This is an idle script (infinite loop) to keep container running. 
/scripts/bootstrap.py:159: SyntaxWarning: invalid escape sequence '\ '
  call('''sed -i -e '/def validate_mysql_user_host(self, host)/a \ \ \ \ \ \ \ \ return host' {}'''
/scripts/bootstrap.py:162: SyntaxWarning: invalid escape sequence '\ '
  call('''sed -i -e '/def validate_mysql_host(self, host)/a \ \ \ \ \ \ \ \ return host' {}'''
[2024-12-09 08:33:02] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
[12/09/2024 08:33:02][upgrade]: The container was recreated, start fix the media symlinks
mv: not replacing '/shared/seafile/seahub-data/avatars/default-non-register.jpg'
mv: not replacing '/shared/seafile/seahub-data/avatars/default.png'
mv: not replacing '/shared/seafile/seahub-data/avatars/groups'
[12/09/2024 08:33:02][upgrade]: Done

Error: .env file not found.
Please follow the upgrade manual to set the .env file.

Traceback (most recent call last):
  File "/scripts/start.py", line 94, in <module>
    main()
  File "/scripts/start.py", line 79, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils.py", line 70, in call
    return subprocess.check_call(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-12.0.4/seafile.sh start' returned non-zero exit status 255.
```
![image](https://github.com/user-attachments/assets/5d6020a0-83b6-4671-b555-8c15bf68839f)
