### ISSUE TITLE
Update version to [2.1.0] for [duplicati]

### ISSUE THREAD

**Issue by qiuf12** [Websoft9/docker-library#1046]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [x] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by qiuf12** [comment]
docker logs duplicati_1cmut
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────
Linuxserver.io version: v2.1.0.2_beta_2024-11-29-ls227
Build-date: 2024-12-07T04:02:10+00:00
───────────────────────────────────────
    
***      Missing encryption key, unable to encrypt your settings database     ***
*** Please set a value for SETTINGS_ENCRYPTION_KEY and recreate the container ***
```

**Comment by qiuf12** [comment]
After setting a value for SETTINGS_ENCRYPTION_KEY，the webpage opens normally，but the account password is incorrect, and the login cannot be found

**Comment by chendelin1982** [comment]
fixed, 

@qiaofeng1227  It need to modify docs because the new version have set password by default

![Image](https://github.com/user-attachments/assets/40d7e37d-5607-4677-8e6e-2b0d8dbf0743)

**Comment by qiaofeng1227** [comment]
![Image](https://github.com/user-attachments/assets/6c35d251-572d-4f8c-947f-8ac6c687433c)

**Comment by qiaofeng1227** [comment]
```
fail: Duplicati.WebserverCore.DuplicatiWebserver[0]
      Unhandled exception
      System.InvalidOperationException: Not a WebSocket request.
         at Microsoft.AspNetCore.WebSockets.WebSocketMiddleware.WebSocketHandshake.AcceptAsync(WebSocketAcceptContext acceptContext)
         at Duplicati.WebserverCore.Middlewares.WebsocketExtensions.<>c__DisplayClass0_0.<<UseNotifications>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Duplicati.WebserverCore.DuplicatiWebserver[0]
      Unhandled exception
      System.InvalidOperationException: Not a WebSocket request.
         at Microsoft.AspNetCore.WebSockets.WebSocketMiddleware.WebSocketHandshake.AcceptAsync(WebSocketAcceptContext acceptContext)
         at Duplicati.WebserverCore.Middlewares.WebsocketExtensions.<>c__DisplayClass0_0.<<UseNotifications>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

```

**Comment by qiaofeng1227** [comment]
add env `DASHBOARD_WEBSOCKET_ENABLED=false` is ok
