### ISSUE TITLE
init should before stopping rails server [redmine]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#147]
docker-compose.yml
```
    entrypoint: ["/docker-entrypoint.sh","rails", "server", "-b", "0.0.0.0"]
    command: [" && cat /my_cmd > cmd.sh && chmod +x /usr/src/redmine/cmd.sh && /usr/src/redmine/cmd.sh"]
```

```
redmine     | 	from bin/rails:4:in `<main>'
redmine     | Exiting
redmine exited with code 1
redmine     | Your Gemfile lists the gem puma (>= 0) more than once.
redmine     | You should probably keep only one of them.
redmine     | Remove any duplicate entries and specify the gem only once.
redmine     | While it's not a problem now, it could cause errors if you change the version of one of them later.
redmine     | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
redmine     | The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
redmine     | The Gemfile's dependencies are satisfied
redmine     | /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/handler.rb:79:in `require': cannot load such file -- rack/handler/ && cat /my_cmd > cmd.sh && chmod +x /usr/src/redmine/cmd.sh && /usr/src/redmine/cmd.sh (LoadError)
redmine     | 	from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/handler.rb:79:in `try_require'
redmine     | 	from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/handler.rb:18:in `get'
redmine     | 	from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:331:in `server'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands/server/server_command.rb:105:in `use_puma?'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands/server/server_command.rb:76:in `print_boot_information'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands/server/server_command.rb:47:in `start'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands/server/server_command.rb:147:in `block in perform'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands/server/server_command.rb:142:in `tap'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands/server/server_command.rb:142:in `perform'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/command/base.rb:69:in `perform'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/command.rb:46:in `invoke'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands.rb:18:in `<top (required)>'
redmine     | 	from bin/rails:4:in `require'
redmine     | 	from bin/rails:4:in `<main>'
redmine     | /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/handler.rb:24:in `const_get': wrong constant name  && cat /my_cmd > cmd.sh && chmod +x /usr/src/redmine/cmd.sh && /usr/src/redmine/cmd.sh (NameError)
redmine     | 	from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/handler.rb:24:in `get'
redmine     | 	from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:331:in `server'


```

**Comment by qiaofeng1227** [comment]
entrypoint: ["/docker-entrypoint.sh","rails", "server", "-b", "0.0.0.0"]
    command: "cat /my_cmd > cmd.sh && chmod +x /usr/src/redmine/cmd.sh && /usr/src/redmine/cmd.sh"
```
redmine     | /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:525:in `handle_argument_error': ERROR: "rails server" was called with arguments ["/my_cmd"] (Thor::InvocationError)
redmine     | Usage: "rails server [puma, thin etc] [options]"
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:34:in `rescue in run'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:20:in `run'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/command/base.rb:69:in `perform'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/command.rb:46:in `invoke'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands.rb:18:in `<top (required)>'
redmine     | 	from bin/rails:4:in `require'
redmine     | 	from bin/rails:4:in `<main>'
redmine     | /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands/server/server_command.rb:139:in `perform': wrong number of arguments (given 1, expected 0) (ArgumentError)
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
redmine     | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/command/base.rb:69:in `perform'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/command.rb:46:in `invoke'
redmine     | 	from /usr/local/bundle/gems/railties-5.2.8/lib/rails/commands.rb:18:in `<top (required)>'
redmine     | 	from bin/rails:4:in `require'
redmine     | 	from bin/rails:4:in `<main>'
redmine exited with code 1
redmine     | Your Gemfile lists the gem puma (>= 0) more than once.
redmine     | You should probably keep only one of them.
redmine     | Remove any duplicate entries and specify the gem only once.
redmine     | While it's not a problem now, it could cause errors if you change the version of one of them later.
redmine     | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
redmine     | The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
redmine     | The Gemfile's dependencies are satisfied
^CGracefully stopping... (press Ctrl+C again to force)

```
