### ISSUE TITLE
500 error for [plausible]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#311]
**Describe the bug**

I can access the interface but 500 error
![image](https://github.com/Websoft9/docker-library/assets/16741975/fbe74f1f-a0d4-4bd2-b436-2605596f6082)

Then, I get the logs of plausible and plausible-db

```
[root@iZ8vb9gse4rc3k7hxgadluZ plausible]# docker logs plausible
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
create Plausible.ClickhouseRepo database if it doesn't exist
Creation of Db successful!
Loading plausible..
Starting dependencies..
Starting repos..
Running migrations for Elixir.Plausible.Repo
Running migrations for Elixir.Plausible.ClickhouseRepo
Migrations successful!
10:31:56.751 [error] #PID<0.3196.0> running PlausibleWeb.Endpoint (connection #PID<0.3193.0>, stream id 2) terminated
Server: 47.92.175.174:9001 (http)
Request: GET /register
** (exit) an exception was raised:
    ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
        (plug 1.13.6) lib/plug/session/cookie.ex:185: Plug.Session.COOKIE.validate_secret_key_base/1
        (plug 1.13.6) lib/plug/session/cookie.ex:177: Plug.Session.COOKIE.derive/3
        (plug 1.13.6) lib/plug/session/cookie.ex:96: Plug.Session.COOKIE.put/4
        (plug 1.13.6) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
        (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug 1.13.6) lib/plug/conn.ex:1690: Plug.Conn.run_before_send/2
        (plug 1.13.6) lib/plug/conn.ex:399: Plug.Conn.send_resp/1
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:1: PlausibleWeb.AuthController.action/2
10:32:01.015 [error] #PID<0.3204.0> running PlausibleWeb.Endpoint (connection #PID<0.3193.0>, stream id 4) terminated
Server: 47.92.175.174:9001 (http)
Request: GET /register
** (exit) an exception was raised:
    ** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
        (plug 1.13.6) lib/plug/session/cookie.ex:185: Plug.Session.COOKIE.validate_secret_key_base/1
        (plug 1.13.6) lib/plug/session/cookie.ex:177: Plug.Session.COOKIE.derive/3
        (plug 1.13.6) lib/plug/session/cookie.ex:96: Plug.Session.COOKIE.put/4
        (plug 1.13.6) lib/plug/session.ex:96: anonymous fn/3 in Plug.Session.before_send/2
        (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug 1.13.6) lib/plug/conn.ex:1690: Plug.Conn.run_before_send/2
        (plug 1.13.6) lib/plug/conn.ex:399: Plug.Conn.send_resp/1
        (plausible 0.0.1) lib/plausible_web/controllers/auth_controller.ex:1: PlausibleWeb.AuthController.action/2
10:32:03.504 [error] #PID<0.3205.0> running PlausibleWeb.Endpoint (connection #PID<0.3193.0>, stream id 5) terminated

```

and 

```

2023-08-01 09:42:18.382 UTC [1] LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-08-01 09:42:18.382 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-08-01 09:42:18.382 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-08-01 09:42:18.384 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-08-01 09:42:18.388 UTC [50] LOG:  database system was shut down at 2023-08-01 09:42:18 UTC
2023-08-01 09:42:18.392 UTC [1] LOG:  database system is ready to accept connections
2023-08-01 09:44:25.105 UTC [1] LOG:  received fast shutdown request
2023-08-01 09:44:25.106 UTC [1] LOG:  aborting any active transactions
2023-08-01 09:44:25.110 UTC [1] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
2023-08-01 09:44:25.110 UTC [51] LOG:  shutting down
2023-08-01 09:44:25.122 UTC [1] LOG:  database system is shut down

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-08-01 09:44:25.468 UTC [1] LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-08-01 09:44:25.469 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-08-01 09:44:25.469 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-08-01 09:44:25.470 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-08-01 09:44:25.473 UTC [22] LOG:  database system was shut down at 2023-08-01 09:44:25 UTC
2023-08-01 09:44:25.477 UTC [1] LOG:  database system is ready to accept connections
2023-08-01 10:27:42.613 UTC [72] FATAL:  database "plausible_db" does not exist
2023-08-01 10:27:42.616 UTC [73] FATAL:  database "plausible_db" does not exist

```

It seem plausible can not connect plausible-db?

**Comment by qiaofeng1227** [comment]
sleep 30 is not friendly, plausible_events_db 加上health。dependent on plausible_events_db‘s health

**Comment by qiaofeng1227** [comment]
wizard error:
![image](https://github.com/Websoft9/docker-library/assets/43192516/6e6ae5ee-2f22-4a09-96b6-46bf621d47b6)

```
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c6d5d7b in /usr/bin/clickhouse
1. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000000716c08d in /usr/bin/clickhouse
2. DB::DatabaseCatalog::assertDatabaseExists(String const&) const @ 0x00000000109fb92f in /usr/bin/clickhouse
3. DB::Context::setCurrentDatabase(String const&) @ 0x000000001094ec32 in /usr/bin/clickhouse
4. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x0000000012616744 in /usr/bin/clickhouse
5. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x000000001261bdb6 in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x0000000012696c12 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x00000000150f4e52 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x00000000150f5c51 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x00000000151ece67 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000151eb45c in /usr/bin/clickhouse
11. ? @ 0x00007f7e4b1fb609 in ?
12. ? @ 0x00007f7e4b120353 in ?
 (version 23.12.2.59 (official build))
2024.01.26 00:57:16.961597 [ 772 ] {} <Error> DynamicQueryHandler: Code: 81. DB::Exception: Database plausible_events_db does not exist. (UNKNOWN_DATABASE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c6d5d7b in /usr/bin/clickhouse
1. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000000716c08d in /usr/bin/clickhouse
2. DB::DatabaseCatalog::assertDatabaseExists(String const&) const @ 0x00000000109fb92f in /usr/bin/clickhouse
3. DB::Context::setCurrentDatabase(String const&) @ 0x000000001094ec32 in /usr/bin/clickhouse
4. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x0000000012616744 in /usr/bin/clickhouse
5. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x000000001261bdb6 in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x0000000012696c12 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x00000000150f4e52 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x00000000150f5c51 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x00000000151ece67 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000151eb45c in /usr/bin/clickhouse
11. ? @ 0x00007f7e4b1fb609 in ?
12. ? @ 0x00007f7e4b120353 in ?
 (version 23.12.2.59 (official build))
```

**Comment by zhilinxinyu** [comment]
Fixed bug: can't create event_db
using the xml files from https://github.com/plausible/hosting/blob/master/docker-compose.yml

    volumes:
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro

-------------------------------------------------------------------------------------------

Other updation:
1. Change restart mode to 'always'
2. Add healthcheck, then remove command "sleep 10"
3. Add env parameter 'BASE_URL' and 'SECRET_KEY_BASE' according to https://github.com/plausible/hosting/blob/master/plausible-conf.env
