### ISSUE TITLE
ERROR Exiting Kafka due to fatal exception (kafka.Kafka$ for [kafka]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#345]
**Describe the bug**

run kafka:latest

```
$ docker logs kafka
[2023-08-08 04:58:55,865] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.lang.IllegalArgumentException: requirement failed: There must be at least one advertised listener.
        at scala.Predef$.require(Predef.scala:281)
        at kafka.server.KafkaConfig.validateAdvertisedListenersNonEmptyForBroker$1(KafkaConfig.scala:2236)
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2305)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2160)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1569)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1492)
        at kafka.Kafka$.buildServer(Kafka.scala:72)
        at kafka.Kafka$.main(Kafka.scala:91)
        at kafka.Kafka.main(Kafka.scala)
kafka 04:59:02.88
kafka 04:59:02.88 Welcome to the Bitnami kafka container
kafka 04:59:02.88 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 04:59:02.88 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 04:59:02.88
kafka 04:59:02.88 INFO  ==> ** Starting Kafka setup **
kafka 04:59:02.95 INFO  ==> ** Kafka setup finished! **

kafka 04:59:02.96 INFO  ==> ** Starting Kafka **

```

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

latest

**CPU**

- [x] amd64, x86 
- [ ] arm64
- [ ] Other (You should describe it)

**Comment by qiaofeng1227** [comment]
```
root@iZbp164zbgh33345jgcgguZ:/data/library/apps/kafka# docker ps
CONTAINER ID   IMAGE                                         COMMAND                  CREATED         STATUS         PORTS                                                                                                             NAMES
d7bf8c6a8f67   bitnami/kafka:3.2                             "/opt/bitnami/script…"   3 seconds ago   Up 1 second    0.0.0.0:9096->9092/tcp, :::9096->9092/tcp                                                                         kafka
5f57109da2f2   ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest   "/cmak/bin/cmak -Dpi…"   3 seconds ago   Up 2 seconds   0.0.0.0:9095->9000/tcp, :::9095->9000/tcp                                                                         kafka-cmak
1a37f1375192   bitnami/zookeeper:latest                      "/opt/bitnami/script…"   3 seconds ago   Up 2 seconds   2888/tcp, 3888/tcp, 8080/tcp, 0.0.0.0:32771->2181/tcp, :::32771->2181/tcp      
```

**Comment by qiaofeng1227** [comment]
```
80a85cbf43:9092 (id: 1001 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to 0a80a85cbf43:9092 (id: 1001 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:298)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:251)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
```

**Comment by chendelin1982** [comment]
not have error 3.6
