### ISSUE TITLE
can not connect db for  plausible

### ISSUE THREAD

**Issue by auaaaa** [Websoft9/docker-library#449]
域名访问失败
![plausible](https://github.com/Websoft9/docker-library/assets/117525450/a303bebe-9257-4c0d-b51f-a147aa10ae1c)
ip访问失败
![QQ图片20231205095538](https://github.com/Websoft9/docker-library/assets/117525450/d432fdff-0447-4e83-a326-67094c3d067f)

**Comment by auaaaa** [comment]
~~~
root@iZj6cfthgfq1z5oggvc2enZ:~# docker logs plausible_3qvav
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
00:49:29.511 [error] Postgrex.Protocol (#PID<0.163.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
00:49:29.511 [error] Postgrex.Protocol (#PID<0.164.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
00:49:29.511 [error] Postgrex.Protocol (#PID<0.183.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
00:49:29.521 [error] Ch.Connection (#PID<0.172.0>) failed to connect: ** (Ch.Error) Code: 81. DB::Exception: Database plausible_events_db doesn't exist. (UNKNOWN_DATABASE) (version 22.6.9.11 (official build))

00:49:29.521 [error] Ch.Connection (#PID<0.171.0>) failed to connect: ** (Ch.Error) Code: 81. DB::Exception: Database plausible_events_db doesn't exist. (UNKNOWN_DATABASE) (version 22.6.9.11 (official build))

00:49:29.547 [error] Postgrex.Protocol (#PID<0.187.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
** (MatchError) no match of right hand side value: {:error, "killed"}
    (plausible 0.0.1) lib/plausible_release.ex:40: anonymous fn/2 in Plausible.Release.createdb/0
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plausible 0.0.1) lib/plausible_release.ex:39: Plausible.Release.createdb/0
    nofile:1: (file)
    (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7

~~~

**Comment by qiaofeng1227** [comment]
plausible有一个服务端[stmp服务器](https://plausible.io/docs/self-hosting-configuration#mailersmtp-setup)

**Comment by chendelin1982** [comment]
> plausible有一个服务端[stmp服务器](https://plausible.io/docs/self-hosting-configuration#mailersmtp-setup)

This is a customer smtp service
