### ISSUE TITLE
kafka and kafka gui 【Redpanda Console】

### ISSUE THREAD

**Issue by lessfrim** [Websoft9/docker-library#450]
<img width="801" alt="1701764222658" src="https://github.com/Websoft9/docker-library/assets/117550670/169e782f-c710-4243-b883-555c314aaecd">

**Comment by lessfrim** [comment]
~~~
[2023-12-07 02:02:59,970] WARN [RequestSendThread controllerId=1001] Controller 1001's connection to broker 6031926ff189:9092 (id: 1001 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to 6031926ff189:9092 (id: 1001 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:298)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:251)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
~~~

**Comment by qiaofeng1227** [comment]
change cmark to efak,redpanda,akhq, it is not work.

**Comment by chendelin1982** [comment]
> akhq

- efak is not have maintenance
- akhq is need lots containers
- redpanda console is independent container for redpanda and kafka
https://github.com/redpanda-data/console?tab=readme-ov-file

**Comment by chendelin1982** [comment]
- [x] SASL for user and password？ bitnami kafka provide environment for this
- [x] redpanda is strong depends on Kafka
- [x] bitnami kafka vs official kafka?   don't allow depends on zookeeper，suggest bitnami kafka
- [x] redpanda console login page? It seem Enterprise function

**Comment by qiaofeng1227** [comment]
```
I have no name!@ece0f7531a6b:/opt/bitnami/kafka$ bin/kafka-topics.sh --create --topic quickstart-events --bootstrap-server localhost:9092
Created topic quickstart-events.
I have no name!@ece0f7531a6b:/opt/bitnami/kafka$ /opt/bitnami/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --consumer.config /opt/bitnami/kafka/config/consumer.properties --topic quickstart-events

```


```
Failed to create user
Redpanda Admin API is not enabled (Status 503)
https://docs.redpanda.com/redpanda-labs/docker-compose/console-plain-login/
```
