### ISSUE TITLE
complete docker compose for rocketchat

### ISSUE THREAD

**Issue by auaaaa** [Websoft9/docker-library#473]
域名访问失败
![QQ图片20231205153703](https://github.com/Websoft9/docker-library/assets/117525450/c127191e-3b70-4e48-baba-5c1edd7d92de)
ip访问失败
![QQ图片20231205141234](https://github.com/Websoft9/docker-library/assets/117525450/834e6493-f616-4ae6-b308-322b51a11933)

**Comment by auaaaa** [comment]
~~~
root@iZj6cfthgfq1z5oggvc2enZ:~# docker logs rocket_mcav8
/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

MongoServerSelectionError: Server selection timed out after 30000 ms
    at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:292:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:11)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:9:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:66:18)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:127:40)
    at AccountsServer._initializeCollection (packages/accounts-base/accounts_common.js:98:20)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:46:23)
    at new AccountsServer (packages/accounts-base/accounts_server.js:30:5)
    at packages/accounts-base/server_main.js:7:12
    at module (packages/accounts-base/server_main.js:19:31)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/packages/accounts-base.js:2219:15
    at /app/bundle/programs/server/packages/accounts-base.js:2226:3 {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'RSGhost',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 7,
        roundTripTime: 0.8940488376831233,
        lastUpdateTime: 5403676,
        lastWriteDate: 0,
        error: null,
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: 30,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'rs01',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}
~~~

**Comment by qiaofeng1227** [comment]
solved
