### ISSUE TITLE
complete docker compose for alfresco

### ISSUE THREAD

**Issue by Camelliw** [Websoft9/docker-library#527]
<img width="604" alt="image" src="https://github.com/Websoft9/docker-library/assets/117551145/a8370151-13c9-4fdd-bfd3-bbb632d1718a">

**Comment by qiaofeng1227** [comment]
```
root@iZj6cfthgfq1z5oggvc2enZ:~# docker logs 037fc10514e1
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/local/tomcat/bin/catalina.sh: line 411: Hqa: No such file or directory
```

**Comment by qiaofeng1227** [comment]
alfresco need encryption password: you can use /src/encryption.py to encryption password

**Comment by qiaofeng1227** [comment]
alfresco  can login.

```
23-Jan-2024 06:25:00.019 INFO [http-nio-8080-exec-9] org.apache.coyote.AbstractProcessor.parseHost The host [alfresco_f62ch-alfresco:8080] is not valid
 Note: further occurrences of request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: The character [_] is never valid in a domain name.
		at org.apache.tomcat.util.http.parser.HttpParser$DomainParseState.next(HttpParser.java:1045)
		at org.apache.tomcat.util.http.parser.HttpParser.readHostDomainName(HttpParser.java:931)
		at org.apache.tomcat.util.http.parser.Host.parse(Host.java:67)
		at org.apache.tomcat.util.http.parser.Host.parse(Host.java:43)
		at org.apache.coyote.AbstractProcessor.parseHost(AbstractProcessor.java:297)
		at org.apache.coyote.http11.Http11Processor.prepareRequest(Http11Processor.java:785)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:368)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:833)
2024-01-23T06:26:51,305 [] WARN  [transport.failover.FailoverTransport] [ActiveMQ Task-1] Failed to connect to [nio://alfresco_f62ch-activemq:61616] after: 20 attempt(s) with hostname can't be null, continuing to retry.
2024-01-23T06:26:51,306 [] WARN  [transport.failover.FailoverTransport] [ActiveMQ Task-1] Failed to connect to [nio://alfresco_f62ch-activemq:61616] after: 20 attempt(s) with hostname can't be null, continuing to retry.
2024-01-23T06:26:51,306 [] WARN  [transport.failover.FailoverTransport] [ActiveMQ Task-1] Failed to connect to [nio://alfresco_f62ch-activemq:61616] after: 20 attempt(s) with hostname can't be null, continuing to retry
```

**Comment by chendelin1982** [comment]
official docker-compose have the same error?
no
