### ISSUE TITLE
Starting example, unable to use editor normally [Onlyoffice Docs]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#548]
After setting up [self signature](https://github.com/Websoft9/docker-library/tree/main/apps/onlyofficedocs/src), starting example, unable to use editor normally

![image](https://github.com/Websoft9/docker-library/assets/62225175/ddfee7da-b405-44cc-b558-4e9f7933d8f7)

![image](https://github.com/Websoft9/docker-library/assets/62225175/c52733fa-d9d1-496d-a08e-16284c8e370c)

logs
```
[2023-12-29T01:24:02.297] [ERROR] [localhost] [119.28.188.16new__2_.docx1703813039645] [uid-1] nodeJS - postData error: url = https://47.76.56.218/example/track?filename=new%20(2).docx&useraddress=119.28.188.16;data = {"key":"119.28.188.16new__2_.docx1703813039645","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxMTkuMjguMTg4LjE2bmV3X18yXy5kb2N4MTcwMzgxMzAzOTY0NSIsInN0YXR1cyI6MSwidXNlcnMiOlsidWlkLTEiXSwiYWN0aW9ucyI6W3sidHlwZSI6MSwidXNlcmlkIjoidWlkLTEifV0sImlhdCI6MTcwMzgxMzA0MiwiZXhwIjoxNzAzODEzMzQyfQ.N0mOdSvhXzPNFQ4AESAVfR-_gGqm6Vy3nrVoinuZdoc"} Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)

```

**Comment by chendelin1982** [comment]
Have test it, work well.   http or https?

**Comment by laozhou0731** [comment]
[Using HTTPS](https://github.com/Websoft9/docker-library/tree/main/apps/onlyofficedocs/src)

**Comment by laozhou0731** [comment]
Official solution:
1.Modify the container configuration file "/etc/onlyoffice/documentserver/default. json" and change the value of the "rejectUnauthorized" parameter to "false".
2. Save the changes and execute "supervisor ctl restart all"
