### ISSUE TITLE
NocoDB无法访问

### ISSUE THREAD

**Issue by wildechair** [Websoft9/docker-library#598]
![image](https://github.com/Websoft9/docker-library/assets/105709702/a3a61747-2db0-4bd2-bb02-1f74871e737d)

![image](https://github.com/Websoft9/docker-library/assets/105709702/05580c60-f284-4c34-a65d-625ca8d448d0)

![image](https://github.com/Websoft9/docker-library/assets/105709702/537655c8-f043-4284-804d-faa89cc0f8f3)

**Comment by wildechair** [comment]
```
Error: Error: Meta database configuration missing database name
    at NcConfig.create (/usr/src/app/docker/main.js:2:1970448)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1410752)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
```

**Comment by qiaofeng1227** [comment]
W9_POWER_PASSWORD->W9_RCODE
