### ISSUE TITLE
run https://hub.docker.com/r/liferay/dxp for testing

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#612]
**What type of your feature request?**  

test https://hub.docker.com/r/liferay/dxp, if can access it, please let @chendelin1982 use and test it

**Comment by half-yutou** [comment]
when use docker run -it -p 8080:8080 liferay/dxp:latest,it stop at:
2024-05-15 06:55:57.340 INFO  [fileinstall-directory-watcher][LicenseManager:-1] DXP Development license validation passed
2024-05-15 06:55:57.340 INFO  [fileinstall-directory-watcher][LicenseManager:-1] License registered for DXP Development

**Comment by half-yutou** [comment]
[root@test001 ~]# docker run -it -p 8848:8080 liferay/dxp:latest -e LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS=119.8.25.33

after setting env at runtime,an warning is still reported

2024-05-15 07:57:16.978 WARN  [http-nio-8080-exec-9][PortalImpl:5507] Set the property "virtual.hosts.valid.hosts" in portal.properties to allow "119.8.25.33" as a domain

**Comment by half-yutou** [comment]
> [root@test001 ~]# docker run -it -p 8848:8080 liferay/dxp:latest -e LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS=119.8.25.33
> 
> after setting env at runtime,an warning is still reported
> 
> 2024-05-15 07:57:16.978 WARN [http-nio-8080-exec-9][PortalImpl:5507] Set the property "virtual.hosts.valid.hosts" in portal.properties to allow "119.8.25.33" as a domain

when docker run, it stop at:
```
2024-05-15 08:57:28.666 INFO  [fileinstall-directory-watcher][LicenseManager:-1] DXP Development license validation passed
2024-05-15 08:57:28.666 INFO  [fileinstall-directory-watcher][LicenseManager:-1] License registered for DXP Development
```
at the same time
1. browser can jump to the default url after specifying the host and port
![image](https://github.com/Websoft9/docker-library/assets/117514010/4bc33c7b-3104-44d2-99f3-8fd025ddb361)

2. when browser jump to the url,server throws a runtime exception:
```
2024-05-15 08:59:02.449 WARN  [http-nio-8080-exec-10][code_jsp:161] {code="500", msg="", uri=/}
java.lang.RuntimeException: Invalid host name 119.8.25.33
        at com.liferay.portal.servlet.filters.validhostname.ValidHostNameFilter.doFilterTry(ValidHostNameFilter.java:31) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:187) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:92) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:95) ~[portal-kernel.jar:?]
        at com.liferay.shielded.container.internal.proxy.FilterWrapper.doFilter(FilterWrapper.java:69) ~[com.liferay.shielded.container.impl.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:179) ~[catalina.jar:9.0.87]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:154) ~[catalina.jar:9.0.87]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) ~[catalina.jar:9.0.87]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:9.0.87]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[catalina.jar:9.0.87]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.87]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.87]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.87]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) [catalina.jar:9.0.87]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-coyote.jar:9.0.87]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.87]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) [tomcat-coyote.jar:9.0.87]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1786) [tomcat-coyote.jar:9.0.87]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.87]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.87]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.87]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) [tomcat-util.jar:9.0.87]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2024-05-15 08:59:02.510 WARN  [http-nio-8080-exec-10][PortalImpl:5507] Set the property "virtual.hosts.valid.hosts" in portal.properties to allow "119.8.25.33" as a domain
```
though we have specify the env about virtual.hosts.valid.hosts.

**Comment by qiaofeng1227** [comment]
```
2024-05-16 07:08:22.018 INFO  [main][StartupHelperUtil:96] There are no patches installed
2024-05-16 07:08:22.116 INFO  [main][LoggingTimer:74] Starting com.liferay.portal.events.StartupHelperUtil#initResourceActions
2024-05-16 07:08:22.139 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.events.StartupHelperUtil#initResourceActions in 23 ms
2024-05-16 07:08:22.156 INFO  [main][LicenseManager:-1] Failed to find directory /opt/liferay/data/license
2024-05-16 07:08:22.156 INFO  [main][LicenseManager:-1] No binary licenses found
2024-05-16 07:08:22.661 INFO  [main][AutoDeployDir:152] Auto deploy scanner started for /opt/liferay/deploy

```

The DXP images come with a 30 day trial license. Older images will be regularly deleted and new images with a new 30 day trial license will be made available.

**Comment by half-yutou** [comment]
the issue to liferay official site:
https://github.com/liferay/liferay-docker/issues/145
