### ISSUE TITLE
complete docker-compose.yml for [onyx]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#633]
**What type of your feature request?**  

https://www.onyx.app

- [x] official architecture research
- [x] test offcial docker
- [ ] complete standardized expression
- [x] developer test and running
- [ ] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [ ] test at Appstore and nginx proxy testing
- [ ] docs
- [ ] siteurl or baseurl
- [ ] more environments from
- [ ] connetion URI
- [ ] ports
- [ ] credentials environment
- [ ] i18n
- [ ] other

**Comment by zhaojing1987** [comment]
其中 index 容器对于比较旧的CPU支持有问题：https://docs.vespa.ai/en/cpu-support.html

**Comment by zhaojing1987** [comment]
后台地址：/admin/indexing/status

**Comment by zhaojing1987** [comment]
已提交docker compose，可以测试

**Comment by qiaofeng1227** [comment]
测试机cpu Intel Xeon Gold 6278C 属于 Cascade Lake 微架构，发布于2019年。Cascade Lake 是 Skylake 的改进版，Skylake 是在 Haswell 之后发布的，index容器还是报错。
```
[root@test2 ~]# docker logs danswer-index-8001
/usr/local/bin/start-container.sh: line 67:    11 Illegal instruction     (core dumped) /opt/vespa/bin/vespa-start-configserver
/usr/local/bin/start-container.sh: line 67:    10 Illegal instruction     (core dumped) /opt/vespa/bin/vespa-start-configserver
/usr/local/bin/start-container.sh: line 67:    10 Illegal instruction     (core dumped) /opt/vespa/bin/vespa-start-configserver
/usr/local/bin/start-container.sh: line 67:    10 Illegal instruction     (core dumped) /opt/vespa/bin/vespa-start-configserver
```


解决方法，将index容器版本升级到最新。

```
Problem running program vespa-detect-hostname => died with signal: illegal instruction (you probably have an older CPU than required, see https://docs.vespa.ai/en/cpu-support.html)

Starting configserver on '7975c11aca22'

Problem running program /opt/vespa/bin/vespa-runserver => died with signal: illegal instruction (you probably have an older CPU than required, see https://docs.vespa.ai/en/cpu-support.html)

Problem running program vespa-detect-hostname => died with signal: illegal instruction (you probably have an older CPU than required, see https://docs.vespa.ai/en/cpu-support.html)

1728618013.058336	7975c11aca22	19	-	vespa-start-services	info	Too low vm.max_map_count [65530] - trying to increase it to 262144

1728618013.058354	7975c11aca22	19	-	vespa-start-services	warning	Could not increase vm.max_map_count - current value [65530] too low, should be at least 262144

Starting config proxy using tcp/7975c11aca22:19070 as config source(s)

Waiting for config proxy to start on '7975c11aca22'
```

**Comment by qiaofeng1227** [comment]
danswer_l5q9w-api-server容器不断重启，
```
NOTICE:   10/11/2024 01:56:57 AM                       setup.py  221: Vespa setup did not succeed. The Vespa service may not be ready yet. Retrying in 5 seconds.
ERROR:    10/11/2024 01:57:02 AM                       setup.py  226: Vespa setup did not succeed. Attempt limit reached. (5)
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/main.py", line 176, in lifespan
    setup_danswer(db_session)
  File "/app/danswer/setup.py", line 120, in setup_danswer
    raise RuntimeError("Could not connect to Vespa within the specified timeout.")
RuntimeError: Could not connect to Vespa within the specified timeout.

ERROR:    Application startup failed. Exiting.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Starting Danswer Api Server
/usr/local/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
WARNING:  ASGI app factory detected. Using it, but please consider setting the --factory flag explicitly.
INFO:     Started server process [13]
INFO:     Waiting for application startup.
NOTICE:   10/11/2024 01:57:16 AM                        main.py  148: System recursion limit set to 1000
NOTICE:   10/11/2024 01:57:16 AM                       users.py   90: Using Auth Type: basic
NOTICE:   10/11/2024 01:57:17 AM                       setup.py   71: Using Embedding model: "nomic-ai/nomic-embed-text-v1"
NOTICE:   10/11/2024 01:57:17 AM                       setup.py   73: Query embedding prefix: "search_query: "
NOTICE:   10/11/2024 01:57:17 AM                       setup.py   74: Passage embedding prefix: "search_document: "
NOTICE:   10/11/2024 01:57:17 AM                       setup.py   78: Reranking is enabled.
NOTICE:   10/11/2024 01:57:17 AM                       setup.py   91: Verifying query preprocessing (NLTK) data is downloaded
NOTICE:   10/11/2024 01:57:17 AM                       setup.py  233: Verifying default connector/credential exist.
NOTICE:   10/11/2024 01:57:17 AM                       setup.py  238: Loading default Prompts and Personas
NOTICE:   10/11/2024 01:57:17 AM                       setup.py  242: Loading built-in tools
NOTICE:   10/11/2024 01:57:17 AM              built_in_tools.py   80: Updated tool: SearchTool
NOTICE:   10/11/2024 01:57:17 AM              built_in_tools.py   80: Updated tool: ImageGenerationTool
NOTICE:   10/11/2024 01:57:17 AM              built_in_tools.py  100: All built-in tools are loaded/verified.
NOTICE:   10/11/2024 01:57:17 AM              built_in_tools.py  143: Added SearchTool to Persona ID: 0
NOTICE:   10/11/2024 01:57:17 AM              built_in_tools.py  143: Added SearchTool to Persona ID: -2
NOTICE:   10/11/2024 01:57:17 AM              built_in_tools.py  147: Completed adding SearchTool to relevant Personas.
NOTICE:   10/11/2024 01:57:17 AM                       setup.py  176: No search config found in KV store.
NOTICE:   10/11/2024 01:57:17 AM                       setup.py  104: Verifying Document Index(s) is/are available.
NOTICE:   10/11/2024 01:57:17 AM                       setup.py  210: Setting up Vespa (attempt 1/5)...
NOTICE:   10/11/2024 01:57:17 AM                       setup.py  221: Vespa setup did not succeed. The Vespa service may not be ready yet. Retrying in 5 seconds.
NOTICE:   10/11/2024 01:57:22 AM                       setup.py  210: Setting up Vespa (attempt 2/5)...
NOTICE:   10/11/2024 01:57:22 AM                       setup.py  221: Vespa setup did not succeed. The Vespa service may not be ready yet. Retrying in 5 seconds.
NOTICE:   10/11/2024 01:57:27 AM                       setup.py  210: Setting up Vespa (attempt 3/5)...
NOTICE:   10/11/2024 01:57:27 AM                       setup.py  221: Vespa setup did not succeed. The Vespa service may not be ready yet. Retrying in 5 seconds.
NOTICE:   10/11/2024 01:57:32 AM                       setup.py  210: Setting up Vespa (attempt 4/5)...
NOTICE:   10/11/2024 01:57:32 AM                       setup.py  221: Vespa setup did not succeed. The Vespa service may not be ready yet. Retrying in 5 seconds
```

**Comment by zhaojing1987** [comment]
请仔细观察相关容器日志：
![image](https://github.com/user-attachments/assets/f7521a84-7261-4be4-8d6b-1d7a5963d64b)

**Comment by chendelin1982** [comment]
@qiaofeng1227 It have renamed to **onyx**, please modify it all meta data

**Comment by qiaofeng1227** [comment]
更新了最新docker-compose.yml，目前画面出不来。
