### ISSUE TITLE
Bug  for Magento

### ISSUE THREAD

**Issue by yuanssssss** [Websoft9/docker-library#668]
**Describe the bug**

When install the Magento, it will spent about 10 minite or later to initialize, and then the magento-cli will exit with the error code 255,
and  can't access the admin page, which return a 404 page. 

the cli log:
```
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
Waiting for bin/magento to be created...
try to download zh_CN.csv...
/data/vendor/magento/language-zh_hans_cn/zh_CN.csv: No such file or directory
try to download zh_CN.csv...
/data/vendor/magento/language-zh_hans_cn/zh_CN.csv: No such file or directory
try to download zh_CN.csv...
--2024-08-12 07:44:12--  https://websoft9.github.io/docker-library/apps/magento/src/zh_CN.csv
Resolving websoft9.github.io (websoft9.github.io)... 185.199.109.153, 185.199.108.153, 185.199.111.153, ...
Connecting to websoft9.github.io (websoft9.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 562817 (550K) [text/csv]
Saving to: '/data/vendor/magento/language-zh_hans_cn/zh_CN.csv'
     0K .......... .......... .......... .......... ..........  9% 20.8M 0s
    50K .......... .......... .......... .......... .......... 18% 81.9M 0s
   100K .......... .......... .......... .......... .......... 27% 69.4M 0s
   150K .......... .......... .......... .......... .......... 36% 92.9M 0s
   200K .......... .......... .......... .......... .......... 45% 89.8M 0s
   250K .......... .......... .......... .......... .......... 54% 96.8M 0s
   300K .......... .......... .......... .......... .......... 63% 61.2M 0s
   350K .......... .......... .......... .......... .......... 72% 93.0M 0s
   400K .......... .......... .......... .......... .......... 81% 78.2M 0s
   450K .......... .......... .......... .......... .......... 90%  133M 0s
   500K .......... .......... .......... .......... ......... 100% 69.8M=0.008s
2024-08-12 07:44:12 (65.2 MB/s) - '/data/vendor/magento/language-zh_hans_cn/zh_CN.csv' saved [562817/562817]
[12-Aug-2024 07:44:22 UTC] PHP Warning:  require(/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php): Failed to open stream: No such file or directory in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:22 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bitnami/php/lib/php') in /data/vendor/composer/autoload_real.php:41

Stack trace:
#0 /data/vendor/composer/autoload_real.php(45): {closure}()
#1 /data/vendor/autoload.php(25): ComposerAutoloaderInit05b95001e03b74fcfe72321278560811::getLoader()
#2 /data/app/autoload.php(51): include('...')
#3 /data/app/bootstrap.php(44): require_once('...')
#4 /data/bin/magento(14): require('...')

}
  thrown in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:22 UTC] PHP Warning:  require(/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php): Failed to open stream: No such file or directory in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:22 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bitnami/php/lib/php') in /data/vendor/composer/autoload_real.php:41

Stack trace:
#0 /data/vendor/composer/autoload_real.php(45): {closure}()
#1 /data/vendor/autoload.php(25): ComposerAutoloaderInit05b95001e03b74fcfe72321278560811::getLoader()
#2 /data/app/autoload.php(51): include('...')
#3 /data/app/bootstrap.php(44): require_once('...')
#4 /data/bin/magento(14): require('...')

}
  thrown in /data/vendor/composer/autoload_real.php on line 41
Set zh_Hans_CN ok ...
54.145.61.233

P
Start to set URL ...
[12-Aug-2024 07:44:23 UTC] PHP Warning:  require(/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php): Failed to open stream: No such file or directory in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:23 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bitnami/php/lib/php') in /data/vendor/composer/autoload_real.php:41

Stack trace:
#0 /data/vendor/composer/autoload_real.php(45): {closure}()
#1 /data/vendor/autoload.php(25): ComposerAutoloaderInit05b95001e03b74fcfe72321278560811::getLoader()
#2 /data/app/autoload.php(51): include('...')
#3 /data/app/bootstrap.php(44): require_once('...')
#4 /data/bin/magento(14): require('...')

}
  thrown in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:23 UTC] PHP Warning:  require(/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php): Failed to open stream: No such file or directory in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:23 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bitnami/php/lib/php') in /data/vendor/composer/autoload_real.php:41

Stack trace:
#0 /data/vendor/composer/autoload_real.php(45): {closure}()
#1 /data/vendor/autoload.php(25): ComposerAutoloaderInit05b95001e03b74fcfe72321278560811::getLoader()
#2 /data/app/autoload.php(51): include('...')
#3 /data/app/bootstrap.php(44): require_once('...')
#4 /data/bin/magento(14): require('...')

}
  thrown in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:23 UTC] PHP Warning:  require(/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php): Failed to open stream: No such file or directory in /data/vendor/composer/autoload_real.php on line 41
[12-Aug-2024 07:44:23 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/data/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/opt/bitnami/php/lib/php') in /data/vendor/composer/autoload_real.php:41

Stack trace:
#0 /data/vendor/composer/autoload_real.php(45): {closure}()
#1 /data/vendor/autoload.php(25): ComposerAutoloaderInit05b95001e03b74fcfe72321278560811::getLoader()
#2 /data/app/autoload.php(51): include('...')
#3 /data/app/bootstrap.php(44): require_once('...')
#4 /data/bin/magento(14): require('...')

}
  thrown in /data/vendor/composer/autoload_real.php on line 41
```

the home and admin page:
![image](https://github.com/user-attachments/assets/56b4afea-81dc-434a-bc18-baaf4f0a0a35)

## Bug source

- [x] Bugs from installation 

## System Environment

**Application Version**

latest

**Comment by chendelin1982** [comment]
fix
