### ISSUE TITLE
complete docker-compose.yml for [immich]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#696]
**What type of your feature request?**  

- [x] [official architecture](https://immich.app/) research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from or configuration file
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by zhaojing1987** [comment]
Completed Docker compose, waiting for contentful data and testing

**Comment by qiaofeng1227** [comment]
upload images cannot show
main container logs:
```
[Nest] 6  - 09/25/2024, 6:23:04 AM   ERROR [Microservices:JobService] Unable to run job handler (backgroundTask/undefined): TypeError: handler is not a function
[Nest] 6  - 09/25/2024, 6:23:04 AM     LOG [Microservices:StorageService] Verifying system mount folder checks
[Nest] 6  - 09/25/2024, 6:23:04 AM   ERROR [Microservices:JobService] TypeError: handler is not a function
    at /usr/src/app/dist/services/job.service.js:148:42
    at Worker.workerHandler [as processFn] (/usr/src/app/dist/repositories/job.repository.js:90:46)
    at Worker.callProcessJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:113:21)
    at Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:39)
    at /usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:202:70
    at Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:30)
    at Worker.run (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:202:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 6  - 09/25/2024, 6:23:04 AM   ERROR [Microservices:JobService] Object:
{}

Error: Missing lock for job 1. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:266:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 09/25/2024, 6:23:04 AM     LOG [Microservices:StorageService] Successfully verified system mount folder checks

```
