### ISSUE TITLE
Can't set init password[gitlab]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#74]
**Describe the bug**

Can't set init password.
env `GITLAB_ROOT_PASSWORD` and `gitlab_rails['initial_root_password']` can't take effective

## refer to

* [username/password not working after docker setup](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6320)
* [set-up-the-initial-password](https://docs.gitlab.com/omnibus/installation/index.html#set-up-the-initial-password)

**Comment by chendelin1982** [comment]
set gitlab_rails['initial_root_password'], error
```
Running handlers:
There was an error running gitlab-ctl reconfigure:

rails_migration[gitlab-rails] (gitlab::database_migrations line 51) had an error: Mixlib::ShellOut::ShellCommandFailed: bash[migrate gitlab-rails database] (/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/resources/rails_migration.rb line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20211222-31-nfe1m2" ----
STDOUT:
STDERR: /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:178:in `[]=': no implicit conversion of Integer into String (TypeError)
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:178:in `block in set_environment'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:177:in `each'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:177:in `set_environment'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:338:in `block in fork_subprocess'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:321:in `fork'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:321:in `fork_subprocess'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:97:in `run_command'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:270:in `run_command'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/mixin/shell_out.rb:170:in `shell_out_command'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/mixin/shell_out.rb:129:in `shell_out_compacted!'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/mixin/shell_out.rb:64:in `shell_out!'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/provider/execute.rb:58:in `block in action_run'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/mixin/why_run.rb:51:in `add_action'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/provider.rb:234:in `converge_by'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/provider/execute.rb:56:in `action_run'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/provider/script.rb:60:in `action_run'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/provider.rb:189:in `run_action'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource.rb:586:in `run_action'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:74:in `run_action'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:108:in `block in run_all_actions'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:108:in `each'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:108:in `run_all_actions'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:132:in `block in converge'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
        from /opt/gitlab/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:130:in `converge'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/provider.rb:246:in `compile_and_converge_action'
        from (eval):2:in `action_run'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/provider.rb:189:in `run_action'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource.rb:586:in `run_action'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:74:in `run_action'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:108:in `block in run_all_actions'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:108:in `each'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:108:in `run_all_actions'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:132:in `block in converge'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
        from /opt/gitlab/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/runner.rb:130:in `converge'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/client.rb:712:in `block in converge'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/client.rb:707:in `catch'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/client.rb:707:in `converge'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/client.rb:731:in `converge_and_save'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/client.rb:288:in `run'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/application.rb:296:in `block in run_chef_client'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/local_mode.rb:42:in `with_server_connectivity'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/application.rb:279:in `run_chef_client'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/application/base.rb:330:in `run_application'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-15.17.4/lib/chef/application.rb:68:in `run'
        from /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-15.17.4/bin/chef-client:25:in `<top (required)>'
        from /opt/gitlab/embedded/bin/chef-client:23:in `load'
        from /opt/gitlab/embedded/bin/chef-client:23:in `<main>'
---- End output of "bash"  "/tmp/chef-script20211222-31-nfe1m2" ----
Ran "bash"  "/tmp/chef-script20211222-31-nfe1m2" returned 1


Notes:
Default admin account has been configured with following details:
Username: root
Password: You didn't opt-in to print initial root password to STDOUT.

NOTE: Because these credentials might be present in your log files in plain text, it is highly recommended to reset the password following https://docs.gitlab.com/ee/security/reset_user_password.html#reset-your-root-password.

Running handlers complete
Chef Infra Client failed. 15 resources updated in 24 seconds

Notes:
Default admin account has been configured with following details:
Username: root
Password: You didn't opt-in to print initial root password to STDOUT.

NOTE: Because these credentials might be present in your log files in plain text, it is highly recommended to reset the password following https://docs.gitlab.com/ee/security/reset_user_password.html#reset-your-root-password.

Thank you for using GitLab Docker Image!
Current version: gitlab-ce=14.5.2-ce.0

Configure GitLab for your system by editing /etc/gitlab/gitlab.rb file
And restart this container to reload settings.
To do it use docker exec:

  docker exec -it gitlab editor /etc/gitlab/gitlab.rb
  docker restart gitlab

For a comprehensive list of configuration options please see the Omnibus GitLab readme
https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md

If this container fails to start due to permission problems try to fix it by executing:

  docker exec -it gitlab update-permissions
  docker restart gitlab

```

**Comment by chendelin1982** [comment]
confirmed solution: 
env GITLAB_ROOT_PASSWORD and gitlab_rails['initial_root_password'] are not suitable for Gitlab Docker.  
You can get the password by
```
sudo docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
```
