### ISSUE TITLE
Update version to [6.11] for [rocketchat] ￥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#809]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub subimt --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by czj69233** [comment]
### docker logs rocketchat_hee04:
```
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
{"level":40,"time":"2024-11-01T08:54:26.232Z","pid":1,"hostname":"64e7b4e8136d","name":"VoIPAsteriskService","msg":"Voip is not enabled. Cant start the service"}
(node:1) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead 
[2024-11-01T08:54:27.900Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: Moleculer v0.14.31 is starting...
[2024-11-01T08:54:27.900Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: Namespace: <not defined>
[2024-11-01T08:54:27.900Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: Node ID: df6566fd-683b-43c0-a9a5-f66e4ce09fc4
[2024-11-01T08:54:27.901Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/REGISTRY: Strategy: RoundRobinStrategy
[2024-11-01T08:54:27.902Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/REGISTRY: Discoverer: LocalDiscoverer
[2024-11-01T08:54:27.903Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: Serializer: EJSONSerializer
[2024-11-01T08:54:27.908Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: Validator: FastestValidator
[2024-11-01T08:54:27.909Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: Registered 13 middleware(s).
[2024-11-01T08:54:27.910Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: Transporter: TcpTransporter
{"level":51,"time":"2024-11-01T08:54:27.930Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Using change streams"}
[2024-11-01T08:54:27.934Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/TRANSIT: Connecting to the transporter...
[2024-11-01T08:54:27.936Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/TRANSPORTER: TCP server is listening on port 45701
[2024-11-01T08:54:27.937Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/TRANSPORTER: UDP Discovery is disabled.
[2024-11-01T08:54:27.937Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/TRANSPORTER: TCP Transporter started.
{"level":40,"time":"2024-11-01T08:54:28.028Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Change stream error. Trying resume after 1 seconds.","err":{"type":"MongoServerError","message":"The $changeStream stage is only supported on replica sets","stack":"MongoServerError: The $changeStream stage is only supported on replica sets\n    at Connection.onMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)\n    at MessageStream.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (events.js:400:28)\n    at MessageStream.emit (domain.js:475:12)\n    at processIncomingData (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at Socket.ondata (internal/streams/readable.js:731:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)","ok":0,"code":40573,"codeName":"Location40573"}}
ufs: temp directory created at "/tmp/ufs"
+------------------------------------------------------------+
|                       SERVER RUNNING                       |
+------------------------------------------------------------+
|                                                            |
|  Rocket.Chat Version: 6.11.1                               |
|       NodeJS Version: 14.21.3 - x64                        |
|      MongoDB Version: 5.0.30                               |
|       MongoDB Engine: wiredTiger                           |
|             Platform: linux                                |
|         Process Port: 3000                                 |
|             Site URL: http://rocketchat.test2.websoft9.cn  |
|     ReplicaSet OpLog: Enabled                              |
|          Commit Hash: 12e000d889                           |
|        Commit Branch: HEAD                                 |
|                                                            |
+------------------------------------------------------------+
[2024-11-01T08:54:28.448Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/REGISTRY: '$node' service is registered.
[2024-11-01T08:54:28.449Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/REGISTRY: 'matrix' service is registered.
[2024-11-01T08:54:28.449Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/$NODE: Service '$node' started.
[2024-11-01T08:54:28.449Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/MATRIX: Service 'matrix' started.
[2024-11-01T08:54:28.450Z] INFO  df6566fd-683b-43c0-a9a5-f66e4ce09fc4/BROKER: ✔ ServiceBroker with 2 service(s) started successfully in 526ms.
{"level":51,"time":"2024-11-01T08:54:29.029Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Using change streams"}
{"level":40,"time":"2024-11-01T08:54:29.030Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Change stream error. Trying resume after 2 seconds.","err":{"type":"MongoServerError","message":"The $changeStream stage is only supported on replica sets","stack":"MongoServerError: The $changeStream stage is only supported on replica sets\n    at Connection.onMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)\n    at MessageStream.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (events.js:400:28)\n    at MessageStream.emit (domain.js:475:12)\n    at processIncomingData (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at Socket.ondata (internal/streams/readable.js:731:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)","ok":0,"code":40573,"codeName":"Location40573"}}
{"level":51,"time":"2024-11-01T08:54:31.031Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Using change streams"}
{"level":40,"time":"2024-11-01T08:54:31.034Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Change stream error. Trying resume after 3 seconds.","err":{"type":"MongoServerError","message":"The $changeStream stage is only supported on replica sets","stack":"MongoServerError: The $changeStream stage is only supported on replica sets\n    at Connection.onMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)\n    at MessageStream.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (events.js:400:28)\n    at MessageStream.emit (domain.js:475:12)\n    at processIncomingData (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at Socket.ondata (internal/streams/readable.js:731:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)","ok":0,"code":40573,"codeName":"Location40573"}}
{"level":51,"time":"2024-11-01T08:54:34.034Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Using change streams"}
{"level":40,"time":"2024-11-01T08:54:34.037Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Change stream error. Trying resume after 4 seconds.","err":{"type":"MongoServerError","message":"The $changeStream stage is only supported on replica sets","stack":"MongoServerError: The $changeStream stage is only supported on replica sets\n    at Connection.onMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)\n    at MessageStream.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (events.js:400:28)\n    at MessageStream.emit (domain.js:475:12)\n    at processIncomingData (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at Socket.ondata (internal/streams/readable.js:731:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)","ok":0,"code":40573,"codeName":"Location40573"}}
{"level":51,"time":"2024-11-01T08:54:38.037Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Using change streams"}
{"level":40,"time":"2024-11-01T08:54:38.038Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Change stream error. Trying resume after 5 seconds.","err":{"type":"MongoServerError","message":"The $changeStream stage is only supported on replica sets","stack":"MongoServerError: The $changeStream stage is only supported on replica sets\n    at Connection.onMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)\n    at MessageStream.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (events.js:400:28)\n    at MessageStream.emit (domain.js:475:12)\n    at processIncomingData (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at Socket.ondata (internal/streams/readable.js:731:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)","ok":0,"code":40573,"codeName":"Location40573"}}
{"level":50,"time":"2024-11-01T08:54:38.414Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"Exception while invoking method loadLocale","err":{"type":"Error","message":"Unknown asset: moment-locales/zh.js","stack":"Error: Unknown asset: moment-locales/zh.js\n    at getAsset (/app/bundle/programs/server/boot.js:303:21)\n    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)\n    at server/lib/getMomentLocale.ts:7:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at packages/ddp-server/livedata_server.js:1855:36\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1854:12)\n    at Server.callAsync (packages/ddp-server/livedata_server.js:1780:17)\n    at app/api/server/v1/misc.ts:621:33\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:621:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}
{"level":51,"time":"2024-11-01T08:54:43.039Z","pid":1,"hostname":"64e7b4e8136d","name":"DatabaseWatcher","msg":"Using change streams"}
{"level":50,"time":"2024-11-01T08:54:47.932Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:55:07.932Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:55:27.934Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:55:36.096Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"Exception while invoking method loadLocale","err":{"type":"Error","message":"Unknown asset: moment-locales/zh.js","stack":"Error: Unknown asset: moment-locales/zh.js\n    at getAsset (/app/bundle/programs/server/boot.js:303:21)\n    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)\n    at server/lib/getMomentLocale.ts:7:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at packages/ddp-server/livedata_server.js:1855:36\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1854:12)\n    at Server.callAsync (packages/ddp-server/livedata_server.js:1780:17)\n    at app/api/server/v1/misc.ts:621:33\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:621:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}
{"level":50,"time":"2024-11-01T08:55:47.934Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:56:07.936Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:56:27.939Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:56:47.940Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:57:07.941Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:57:27.942Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:57:47.944Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:58:07.946Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:58:27.948Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:58:47.949Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:59:07.950Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:59:27.950Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T08:59:47.952Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T09:00:07.953Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T09:00:27.954Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T09:00:47.955Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T09:01:07.958Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T09:01:27.958Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T09:01:47.959Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
{"level":50,"time":"2024-11-01T09:02:07.960Z","pid":1,"hostname":"64e7b4e8136d","name":"System","msg":"No real time data received recently"}
```
### screenshoot:
![image](https://github.com/user-attachments/assets/0ea47a69-715d-4e46-afa9-dce9c4548330)
![image](https://github.com/user-attachments/assets/407bbdcc-5115-4efb-9229-294ab9983369)
![image](https://github.com/user-attachments/assets/8d9769cb-7c70-415a-a956-2dd0ca8369ed)
