### ISSUE TITLE
ERROR: org.graylog2.bootstrap.prefl...[graylog]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#83]
**Describe the bug**

graylog: 4.3.0 

```
2022-05-28 02:32:34,652 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:22}] to mongo:27017
2022-05-28 02:32:34,700 INFO : org.mongodb.driver.connection - Closed connection [connectionId{localValue:2, serverValue:22}] to mongo:27017 because the pool has been closed.
2022-05-28 02:32:34,704 INFO : org.graylog2.bootstrap.preflight.MongoDBPreflightCheck - Connected to MongoDB version 4.2.20
2022-05-28 02:32:34,990 INFO : org.graylog2.bootstrap.preflight.SearchDbPreflightCheck - Connected to (Elastic/Open)Search version <Elasticsearch:7.16.3>
2022-05-28 02:32:35,014 ERROR: org.graylog2.bootstrap.preflight.PreflightCheckService - Preflight check failed with error: Journal directory </usr/share/graylog/data/journal> has not enough free space (4387 MB) to contain 'message_journal_max_size = 5120 MB'
Exception in thread "main" org.graylog2.bootstrap.preflight.PreflightCheckException: Journal directory </usr/share/graylog/data/journal> has not enough free space (4387 MB) to contain 'message_journal_max_size = 5120 MB'
        at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.checkJournalDirSizeAndType(DiskJournalPreflightCheck.java:71)
        at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.runCheck(DiskJournalPreflightCheck.java:62)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
        at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51)
        at org.graylog2.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:135)
        at org.graylog2.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:126)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:292)

```

**Comment by chendelin1982** [comment]
Have solved.  
reason: disk space not enough, may need 10G?
