### ISSUE TITLE
Update version to [6.0] for [Redmine]for ￥10

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#951]
**What type of your feature request?**  

Bitnami have update it Redmine to 6.x at AWS

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs redmine_dm3ks
~~~
```
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)

          raise ArgumentError, "Missing `secret_key_base` for '#{Rails.env}' environment, set this string with `bin/rails credentials:edit`"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application/configuration.rb:519:in `secret_key_base='
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application/configuration.rb:503:in `secret_key_base'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:470:in `secret_key_base'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:205:in `block in message_verifiers'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/message_verifiers.rb:132:in `build'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/messages/rotation_coordinator.rb:85:in `block in build_with_rotations'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/messages/rotation_coordinator.rb:85:in `map'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/messages/rotation_coordinator.rb:85:in `build_with_rotations'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/messages/rotation_coordinator.rb:19:in `[]'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:232:in `message_verifier'
/usr/local/bundle/gems/activerecord-7.2.2/lib/active_record/railtie.rb:355:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:62:in `block in on_load'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:61:in `each'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:61:in `on_load'
/usr/local/bundle/gems/activerecord-7.2.2/lib/active_record/railtie.rb:354:in `block (2 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:77:in `each'
/usr/local/bundle/gems/activesupport-7.2.2/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application/finisher.rb:94:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:435:in `initialize!'
/usr/src/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/bundle/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:411:in `require_environment!'
/usr/local/bundle/gems/railties-7.2.2/lib/rails/application.rb:559:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

### screenshoot
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/39c5ee76-406d-4428-9410-cb1151018e58">
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/258a4725-ae14-48ec-bab4-79eaa16b2e5d">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/bb47fc31-7a83-4418-b8db-11128b0f4c5b">

**Comment by jinsheng200303** [comment]
## Modify “REDMINE_SECRET_KEY_BASE” to "SECRET_KEY_BASE" at docker-compose.yml
~~~
...
environment:
--
  | REDMINE_DB_MYSQL: $W9_ID-mysql
  | REDMINE_DB_USERNAME: $W9_ID
  | REDMINE_DB_DATABASE: $W9_ID
  | REDMINE_DB_PASSWORD: $W9_POWER_PASSWORD
  | REDMINE_PLUGINS_MIGRATE: 1
  | SECRET_KEY_BASE: supersecretkey
...
~~~

### docker logs
~~~
docker logs redmine_dm3ks
~~~
```
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.6-p108) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: production
*          PID: 1
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
I, [2024-11-18T03:08:10.587318 #1]  INFO -- : Started GET "/" for 175.8.127.8 at 2024-11-18 03:08:10 +0000
I, [2024-11-18T03:08:10.588287 #1]  INFO -- : Processing by WelcomeController#index as HTML
I, [2024-11-18T03:08:10.639343 #1]  INFO -- :   Current user: anonymous
I, [2024-11-18T03:08:10.706444 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 22.3ms | GC: 0.8ms)
I, [2024-11-18T03:08:10.706760 #1]  INFO -- : Completed 200 OK in 118ms (Views: 21.1ms | ActiveRecord: 17.3ms (28 queries, 2 cached) | GC: 11.8ms)
I, [2024-11-18T03:10:30.596823 #1]  INFO -- : Started GET "/login" for 175.8.127.8 at 2024-11-18 03:10:30 +0000
I, [2024-11-18T03:10:30.597438 #1]  INFO -- : Processing by AccountController#login as HTML
I, [2024-11-18T03:10:30.600629 #1]  INFO -- :   Current user: anonymous
I, [2024-11-18T03:10:30.614160 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 12.2ms | GC: 0.4ms)
I, [2024-11-18T03:10:30.614378 #1]  INFO -- : Completed 200 OK in 17ms (Views: 11.3ms | ActiveRecord: 1.8ms (9 queries, 1 cached) | GC: 0.4ms)
I, [2024-11-18T03:10:39.964155 #1]  INFO -- : Started POST "/login" for 175.8.127.8 at 2024-11-18 03:10:39 +0000
I, [2024-11-18T03:10:39.964757 #1]  INFO -- : Processing by AccountController#login as HTML
I, [2024-11-18T03:10:39.964801 #1]  INFO -- :   Parameters: {"authenticity_token"=>"awsKKhajoVdinkSFh2jDH2EnpNUgJ_vC5cIU3glhzNq82iPcJpSS8QFLkHA1UzWGB9aAgBMXT1EnXItZ22jgsA", "back_url"=>"/", "username"=>"admin", "password"=>"[FILTERED]", "login"=>"登录"}
I, [2024-11-18T03:10:39.967064 #1]  INFO -- :   Current user: anonymous
I, [2024-11-18T03:10:39.971186 #1]  INFO -- : Successful authentication for 'admin' from 175.8.127.8 at 2024-11-18 03:10:39 UTC
I, [2024-11-18T03:10:39.984750 #1]  INFO -- : Redirected to http://redmine.test2.websoft9.cn/
I, [2024-11-18T03:10:39.984880 #1]  INFO -- : Completed 302 Found in 20ms (ActiveRecord: 7.2ms (10 queries, 0 cached) | GC: 1.2ms)
I, [2024-11-18T03:10:40.175874 #1]  INFO -- : Started GET "/" for 175.8.127.8 at 2024-11-18 03:10:40 +0000
I, [2024-11-18T03:10:40.176396 #1]  INFO -- : Processing by WelcomeController#index as HTML
I, [2024-11-18T03:10:40.182067 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-11-18T03:10:40.183352 #1]  INFO -- : Redirected to http://redmine.test2.websoft9.cn/my/password
I, [2024-11-18T03:10:40.183438 #1]  INFO -- : Filter chain halted as :check_password_change rendered or redirected
I, [2024-11-18T03:10:40.183540 #1]  INFO -- : Completed 302 Found in 7ms (ActiveRecord: 2.4ms (6 queries, 0 cached) | GC: 0.0ms)
I, [2024-11-18T03:10:40.375736 #1]  INFO -- : Started GET "/my/password" for 175.8.127.8 at 2024-11-18 03:10:40 +0000
I, [2024-11-18T03:10:40.376334 #1]  INFO -- : Processing by MyController#password as HTML
I, [2024-11-18T03:10:40.379400 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-11-18T03:10:40.397527 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 17.3ms | GC: 0.0ms)
I, [2024-11-18T03:10:40.397761 #1]  INFO -- : Completed 200 OK in 21ms (Views: 13.2ms | ActiveRecord: 5.3ms (7 queries, 0 cached) | GC: 0.0ms)
I, [2024-11-18T03:10:53.235298 #1]  INFO -- : Started POST "/my/password" for 175.8.127.8 at 2024-11-18 03:10:53 +0000
I, [2024-11-18T03:10:53.235850 #1]  INFO -- : Processing by MyController#password as HTML
I, [2024-11-18T03:10:53.235904 #1]  INFO -- :   Parameters: {"authenticity_token"=>"zxLnhjUjraHNMO7_JCPwnEPZGMJezUNk1VIX1BQdTsnBJWxsec6FTPmvWepJbhLqS5DC5UrvjgFQkZ0ti0K7xw", "password"=>"[FILTERED]", "new_password"=>"[FILTERED]", "new_password_confirmation"=>"[FILTERED]", "commit"=>"应用"}
I, [2024-11-18T03:10:53.239002 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-11-18T03:10:53.259976 #1]  INFO -- : Redirected to http://redmine.test2.websoft9.cn/my/account
I, [2024-11-18T03:10:53.260081 #1]  INFO -- : Completed 302 Found in 24ms (ActiveRecord: 10.1ms (13 queries, 0 cached) | GC: 0.0ms)
I, [2024-11-18T03:10:53.459266 #1]  INFO -- : Started GET "/my/account" for 175.8.127.8 at 2024-11-18 03:10:53 +0000
I, [2024-11-18T03:10:53.459814 #1]  INFO -- : Processing by MyController#account as HTML
I, [2024-11-18T03:10:53.462769 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-11-18T03:10:53.635682 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 170.6ms | GC: 35.8ms)
I, [2024-11-18T03:10:53.635878 #1]  INFO -- : Completed 200 OK in 176ms (Views: 165.0ms | ActiveRecord: 7.2ms (26 queries, 0 cached) | GC: 35.8ms)
I, [2024-11-18T03:10:56.063113 #1]  INFO -- : Started PUT "/my/account" for 175.8.127.8 at 2024-11-18 03:10:56 +0000
I, [2024-11-18T03:10:56.063740 #1]  INFO -- : Processing by MyController#account as HTML
I, [2024-11-18T03:10:56.063804 #1]  INFO -- :   Parameters: {"authenticity_token"=>"9NQRxUQaZWU2ObG6gc6etyIV0h69HioJpCEKb0lk1rL645ovCPdNiAKmBq_sg3zBKlwIOak852wh4oCW1jsjvA", "user"=>{"firstname"=>"Redmine", "lastname"=>"Admin", "mail"=>"admin@example.net", "language"=>"", "mail_notification"=>"all", "notified_project_ids"=>[""]}, "commit"=>"保存", "pref"=>{"no_self_notified"=>"1", "auto_watch_on"=>["", "issue_created", "issue_contributed_to"], "hide_mail"=>"1", "time_zone"=>"", "comments_sorting"=>"asc", "warn_on_leaving_unsaved"=>"1", "textarea_font"=>"", "recently_used_projects"=>"3", "history_default_tab"=>"notes", "toolbar_language_options"=>"c,cpp,csharp,css,diff,go,groovy,html,java,javascript,objc,perl,php,python,r,ruby,sass,scala,shell,sql,swift,xml,yaml", "default_issue_query"=>"", "default_project_query"=>""}}
I, [2024-11-18T03:10:56.067036 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-11-18T03:10:56.108417 #1]  INFO -- : Redirected to http://redmine.test2.websoft9.cn/my/account
I, [2024-11-18T03:10:56.108549 #1]  INFO -- : Completed 302 Found in 45ms (ActiveRecord: 4.9ms (9 queries, 0 cached) | GC: 0.7ms)
I, [2024-11-18T03:10:56.285687 #1]  INFO -- : Started GET "/my/account" for 175.8.127.8 at 2024-11-18 03:10:56 +0000
I, [2024-11-18T03:10:56.286235 #1]  INFO -- : Processing by MyController#account as HTML
I, [2024-11-18T03:10:56.289078 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-11-18T03:10:56.314632 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 24.2ms | GC: 0.0ms)
I, [2024-11-18T03:10:56.314826 #1]  INFO -- : Completed 200 OK in 28ms (Views: 21.5ms | ActiveRecord: 4.0ms (21 queries, 0 cached) | GC: 0.0ms)
I, [2024-11-18T03:10:58.523252 #1]  INFO -- : Started GET "/admin" for 175.8.127.8 at 2024-11-18 03:10:58 +0000
I, [2024-11-18T03:10:58.523850 #1]  INFO -- : Processing by AdminController#index as HTML
I, [2024-11-18T03:10:58.526973 #1]  INFO -- :   Current user: admin (id=1)
I, [2024-11-18T03:10:58.543933 #1]  INFO -- :   Rendered layout layouts/admin.html.erb (Duration: 11.0ms | GC: 0.0ms)
I, [2024-11-18T03:10:58.544150 #1]  INFO -- : Completed 200 OK in 20ms (Views: 11.0ms | ActiveRecord: 3.2ms (10 queries, 0 cached) | GC: 0.0ms)
I, [2024-11-18T03:11:04.459869 #1]  INFO -- : Started GET "/admin/info" for 175.8.127.8 at 2024-11-18 03:11:04 +0000
I, [2024-11-18T03:11:04.460422 #1]  INFO -- : Processing by AdminController#info as HTML
I, [2024-11-18T03:11:04.463887 #1]  INFO -- :   Current user: admin (id=1)
sh: 1: cvs: not found
I, [2024-11-18T03:11:04.851756 #1]  INFO -- :   Rendered layout layouts/admin.html.erb (Duration: 342.4ms | GC: 0.0ms)
I, [2024-11-18T03:11:04.851972 #1]  INFO -- : Completed 200 OK in 391ms (Views: 342.1ms | ActiveRecord: 3.4ms (7 queries, 0 cached) | GC: 0.0ms)
2024-11-18 03:12:07 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
2024-11-18 03:12:13 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
I, [2024-11-18T03:12:16.463362 #1]  INFO -- : Started GET "/" for 199.45.154.137 at 2024-11-18 03:12:16 +0000
I, [2024-11-18T03:12:16.463873 #1]  INFO -- : Processing by WelcomeController#index as HTML
I, [2024-11-18T03:12:16.465926 #1]  INFO -- :   Current user: anonymous
I, [2024-11-18T03:12:16.480395 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 9.9ms | GC: 1.1ms)
I, [2024-11-18T03:12:16.480605 #1]  INFO -- : Completed 200 OK in 17ms (Views: 10.2ms | ActiveRecord: 2.1ms (10 queries, 2 cached) | GC: 1.1ms)
I, [2024-11-18T03:12:19.980626 #1]  INFO -- : Started GET "/" for 199.45.154.137 at 2024-11-18 03:12:19 +0000
I, [2024-11-18T03:12:19.981185 #1]  INFO -- : Processing by WelcomeController#index as */*
I, [2024-11-18T03:12:19.983069 #1]  INFO -- :   Current user: anonymous
I, [2024-11-18T03:12:19.995809 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 8.9ms | GC: 0.6ms)
I, [2024-11-18T03:12:19.996008 #1]  INFO -- : Completed 200 OK in 15ms (Views: 9.2ms | ActiveRecord: 1.7ms (9 queries, 2 cached) | GC: 0.6ms)
I, [2024-11-18T03:12:20.012752 #1]  INFO -- : Started GET "/favicon.ico" for 199.45.154.137 at 2024-11-18 03:12:20 +0000
```

### screenshoot
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/8bdb622f-64bf-46e0-bbf0-d35acaf5b8fe">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ce868b52-278d-4473-a878-86c8c6655f67">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5afeb4d1-f11c-4e70-ba13-c00224c991c9">
