### ISSUE TITLE
Update version to [3.4.1] for [chat2db] ¥10

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#960]
**What type of your feature request?**  

Change the W9_VERSION to target version number at `.env` and test it

**Research and development steps your need to do**  

- [x] Check the official installation docs of this application
- [x] Add a comment with docker logs
- [x] If need to update documentation, add issue at [Websoft9 docs](https://github.com/websoft9/doc.websoft9.com)

**How to commit your change to [docker-library](https://github.com/Websoft9/docker-library)?**   

   ```
   docker exec -it websoft9-apphub bash
   apphub commit --appid --github_token
   ```

**Testing steps**   

- [x] Upload your sreenshoot to PR
- [ ] Automation testing when submit PR to dev branch
- [x] System testing for dev branch

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs chat2db_obj70
~~~
```
01:49:07.652 [main] WARN ai.chat2db.server.tools.common.util.ConfigUtils -- VERSION_FILE is null

2024-11-28 01:49:51.706  INFO 1 --- [io-10824-exec-1] c.s.w.s.e.EasyControllerExceptionHandler.100 : c1f37b293e8e4822935ec6fc723c1aa8 | ModelAndView business exception occurred/:ModelAndView [view="redirect:/login?callback=/"; model=null]

ai.chat2db.server.tools.common.exception.RedirectBusinessException: common.redirect
        at ai.chat2db.server.web.start.config.config.Chat2dbWebMvcConfigurer$2.preHandle(Chat2dbWebMvcConfigurer.java:154)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:146)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1076)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at ai.chat2db.server.web.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:33)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:76)
        at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at ai.chat2db.server.web.start.log.LogOncePerRequestFilter.doFilterInternal(LogOncePerRequestFilter.java:32)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)

2024-11-28 01:49:52.282  WARN 1 --- [io-10824-exec-3] a.c.s.tools.common.util.ConfigUtils     .79 : aeec66e486b44f55869329e2e1e9f2c5 | VERSION_FILE is null
2024-11-28 01:49:52.283 ERROR 1 --- [io-10824-exec-3] a.c.s.w.a.c.system.SystemController     .58 : aeec66e486b44f55869329e2e1e9f2c5 | clientVersion:null,version:null
```

**Comment by qiaofeng1227** [comment]
本来是升级chat2db，但是发现未升级的3.4.0也会日志报错（说明我们这个产品就没有做好），需要消除日志错误。

**Comment by zhaojing1987** [comment]
这个根本就不是错误，只是一个 重定向异常(common.redirect)，在这里具体是由于用户没有登录，会重定向到登录页面，仅此而已！

**Comment by jinsheng200303** [comment]
### docker logs
~~~
docker logs chat2db_6m2gm
~~~

```
01:35:59.982 [main] WARN ai.chat2db.server.tools.common.util.ConfigUtils -- VERSION_FILE is null
01:36:00.012 [main] INFO ai.chat2db.server.tools.common.util.ConfigUtils -- set config:{"systemUuid":"75538d41de8c4f8dae49b2f51bc81c4a"}
01:36:00.020 [main] INFO ai.chat2db.server.tools.common.util.ConfigUtils -- set config:{"jwtSecretKey":"d4bff8dc282f45a1a6dde78198590066","systemUuid":"75538d41de8c4f8dae49b2f51bc81c4a"}
启动耗时：465ms

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.0)

2024-12-06 01:36:01.016  INFO 1 --- [           main] a.chat2db.server.web.start.Application  .51 :  | Starting Application v2.0.0-SNAPSHOT using Java 17.0.2 with PID 1 (/app/chat2db-server-web-start.jar started by root in /app)
2024-12-06 01:36:01.022  INFO 1 --- [           main] a.chat2db.server.web.start.Application  .639 :  | The following 1 profile is active: "release"
2024-12-06 01:36:03.776  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer .108 :  | Tomcat initialized with port(s): 10824 (http)
2024-12-06 01:36:03.787  INFO 1 --- [           main] o.apache.catalina.core.StandardService  .173 :  | Starting service [Tomcat]
2024-12-06 01:36:03.788  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine   .173 :  | Starting Servlet engine: [Apache Tomcat/10.1.8]
2024-12-06 01:36:03.876  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]      .173 :  | Initializing Spring embedded WebApplicationContext
2024-12-06 01:36:03.877  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext.291 :  | Root WebApplicationContext: initialization completed in 2753 ms
2024-12-06 01:36:05.716  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping   .57 :  | Adding welcome page template: index
2024-12-06 01:36:05.928  WARN 1 --- [           main] o.thymeleaf.templatemode.TemplateMode   .92 :  | [THYMELEAF][main] Unknown Template Mode 'HTML5'. Must be one of: 'HTML', 'XML', 'TEXT', 'JAVASCRIPT', 'CSS', 'RAW'. Using default Template Mode 'HTML'.
2024-12-06 01:36:05.961  INFO 1 --- [           main] a.c.s.w.s.config.oauth.SaLogForSlf4j    .27 :  | 全局组件 SaLog 载入成功: ai.chat2db.server.web.start.config.oauth.SaLogForSlf4j
____ ____    ___ ____ _  _ ____ _  _ 
[__  |__| __  |  |  | |_/  |___ |\ | 
___] |  |     |  |__| | \_ |___ | \| 
https://sa-token.cc (v1.34.0)
2024-12-06 01:36:05.963  INFO 1 --- [           main] a.c.s.w.s.config.oauth.SaLogForSlf4j    .27 :  | 全局配置 SaTokenConfig [tokenName=CHAT2DB, timeout=2592000, activityTimeout=-1, isConcurrent=true, isShare=true, maxLoginCount=12, isReadBody=true, isReadHeader=true, isReadCookie=true, isWriteHeader=true, tokenStyle=uuid, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=true, logLevel=trace, logLevelInt=1, jwtSecretKey=d4bff8dc282f45a1a6dde78198590066, basic=, currDomain=null, sameTokenTimeout=86400, checkSameToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null]] 
2024-12-06 01:36:05.971  INFO 1 --- [           main] a.c.s.w.s.config.oauth.SaLogForSlf4j    .27 :  | 全局组件 SaTokenContext 载入成功: cn.dev33.satoken.spring.SaTokenContextForSpringInJakartaServlet
2024-12-06 01:36:05.974  INFO 1 --- [           main] a.c.s.w.s.config.oauth.SaLogForSlf4j    .27 :  | 全局组件 SaJsonTemplate 载入成功: cn.dev33.satoken.spring.json.SaJsonTemplateForJackson
```

### screenshoot
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/d7cf6899-436b-49d9-b970-66c248242d75">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/0bcdcc0c-6d4f-4c1e-83a8-1633b799284b">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/24424453-6daf-4042-bf80-37de22a3d77c">
